In [136]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from keras.layers import Dense
from keras.models import Sequential

import pickle

In [121]:
df = pd.read_csv("Churn_Modelling.csv")

In [122]:
df.head()

,CustomerId,Name,HasCrCard,CreditScore,Geography,Gender,Age,Tenure,Balance,PrdtcCnts,ActivedMmbr,EstimatedSalary,Exited
0,15634602,Hargrave,1,619,France,Female,42,2,0.00,1,1,101348.88,1
1,15647311,Hill,0,608,Spain,Female,41,1,83807.86,1,1,112542.58,0
2,15619304,Onio,1,502,France,Female,42,8,159660.80,3,0,113931.57,1
3,15701354,Boni,0,699,France,Female,39,1,0.00,2,0,93826.63,0
4,15737888,Mitchell,1,850,Spain,Female,43,2,125510.82,1,1,79084.10,0

In [123]:
df = df.drop(['CustomerId', 'Name'], axis = 1)

In [124]:
df.head()

,HasCrCard,CreditScore,Geography,Gender,Age,Tenure,Balance,PrdtcCnts,ActivedMmbr,EstimatedSalary,Exited
0,1,619,France,Female,42,2,0.00,1,1,101348.88,1
1,0,608,Spain,Female,41,1,83807.86,1,1,112542.58,0
2,1,502,France,Female,42,8,159660.80,3,0,113931.57,1
3,0,699,France,Female,39,1,0.00,2,0,93826.63,0
4,1,850,Spain,Female,43,2,125510.82,1,1,79084.10,0

In [125]:
df.isnull().sum()

HasCrCard          0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
PrdtcCnts          0
ActivedMmbr        0
EstimatedSalary    0
Exited             0
dtype: int64

In [126]:
le = LabelEncoder()
df["Gender"] = le.fit_transform(df["Gender"])

In [127]:
ohe = OneHotEncoder()
ohe_geo = ohe.fit_transform(df[['Geography']])

In [128]:
ohe_geo

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [129]:
ohe_geo.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], shape=(10000, 3))

In [130]:
ohe.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [131]:
df_geo = pd.DataFrame(ohe_geo.toarray(), columns = ohe.get_feature_names_out(['Geography']))

In [132]:
df_geo.head()

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0
1               0.0                0.0              1.0
2               1.0                0.0              0.0
3               1.0                0.0              0.0
4               0.0                0.0              1.0

In [133]:
df = pd.concat([df.drop('Geography', axis=1), df_geo], axis=1)
# df = df.drop('Geography', axis = 1)
# df = pd.concat([df, df_geo], axis=1)

In [134]:
df

,HasCrCard,CreditScore,Gender,Age,Tenure,Balance,PrdtcCnts,ActivedMmbr,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,1,619,0,42,2,0.00,1,1,101348.88,1,1.0,0.0,0.0
1,0,608,0,41,1,83807.86,1,1,112542.58,0,0.0,0.0,1.0
2,1,502,0,42,8,159660.80,3,0,113931.57,1,1.0,0.0,0.0
3,0,699,0,39,1,0.00,2,0,93826.63,0,1.0,0.0,0.0
4,1,850,0,43,2,125510.82,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,1,771,1,39,5,0.00,2,0,96270.64,0,1.0,0.0,0.0
9996,1,516,1,35,10,57369.61,1,1,101699.77,0,1.0,0.0,0.0
9997,0,709,0,36,7,0.00,1,1,42085.58,1,1.0,0.0,0.0
9998,1,772,1,42,3,75075.31,2,0,92888.52,1,0.0,1.0,0.0
9999,1,792,0,28,4,130142.79,1,0,38190.78,0,1.0,0.0,0.0

In [138]:
with open('le.pkl','wb') as file:
    pickle.dump(le, file)

with open('ohe.pkl','wb') as file:
    pickle.dump(ohe, file)

In [139]:
input_data = df.iloc[:,2:12]

In [140]:
output_data = df.iloc[:,-1]

In [141]:
output_data.head(2)

0    1
1    0
Name: Exited, dtype: int64

In [142]:
input_data.shape

(10000, 10)

In [143]:

X_train,X_test,Y_train,Y_test = train_test_split(input_data,output_data,test_size = 0.2, random_state =43)

In [145]:
ss = StandardScaler()

In [146]:
ss.fit_transform(input_data)

array([[ 0.64609167, -0.32622142, -0.90188624, ..., -0.91158349,
         0.97024255,  0.02188649],
       [-1.54776799, -0.44003595,  1.51506738, ..., -0.91158349,
         0.97024255,  0.21653375],
       [ 0.64609167, -1.53679418, -0.90188624, ...,  2.52705662,
        -1.03067011,  0.2406869 ],
       ...,
       [-1.54776799,  0.60498839, -0.90188624, ..., -0.91158349,
         0.97024255, -1.00864308],
       [ 0.64609167,  1.25683526,  0.30659057, ...,  0.80773656,
        -1.03067011, -0.12523071],
       [ 0.64609167,  1.46377078, -0.90188624, ..., -0.91158349,
        -1.03067011, -1.07636976]], shape=(10000, 10))

In [148]:
ann = Sequential()

In [149]:
ann.add(Dense(8,input_dim = 10, activation="relu")) # first layer - 8 is the no. of nodes in first layer, and dimension is the no. of columns to be inserted
ann.add(Dense(6, activation="relu")) # the number of nodes should decrase as the layer increases 
ann.add(Dense(4, activation="relu"))
ann.add(Dense(3, activation="relu"))
ann.add(Dense(2, activation="relu"))
ann.add(Dense(1, activation="sigmoid")) # at last the activation should be sigmoid because here the output is binary

C:\Users\Lalit Chandra\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [150]:
ann.compile(optimizer="adam",loss="binary_crossentropy", metrics=['accuracy'])

In [151]:
ann.fit(X_train,Y_train, batch_size = 100, epochs = 10)

Epoch 1/10
80/80 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7966 - loss: 0.6828
Epoch 2/10
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7966 - loss: 0.6611
Epoch 3/10
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 960us/step - accuracy: 0.7968 - loss: 0.6415
Epoch 4/10
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7968 - loss: 0.6241
Epoch 5/10
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.7969 - loss: 0.6086
Epoch 6/10
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 947us/step - accuracy: 0.7969 - loss: 0.5949
Epoch 7/10
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7969 - loss: 0.5827
Epoch 8/10
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7969 - loss: 0.5720
Epoch 9/10
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step - accuracy: 0.7969 - loss: 0.5625
Epoch 10/10
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 995us/step - accuracy: 0.7969 - loss: 0.5542

In [152]:
pred = []
Y = ann.predict(X_test)
for i in Y:
    if i<0.5:
        pred.append(0)
    elif i>0.5:
        pred.append(1)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

In [153]:
from sklearn.metrics import accuracy_score

In [154]:
accuracy_score(Y_test,pred)*100

79.4

In [155]:
pred1 = []
X = ann.predict(X_train)
for i in X:
    if i<0.5:
        pred1.append(0)
    elif i>0.5:
        pred1.append(1)

250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 483us/step

In [156]:
accuracy_score(Y_train,pred1)*100

79.6875